### ISSUE TITLE
Application cannot be closed using Cmd-Q on macOS

### ISSUE THREAD

**Issue by albemala** [eveningkid/reacto#14]
I believe this is some kind of standard for macOS apps so it would be good to have it.

**Comment by eveningkid** [comment]
Agreed. This was fixed with PR #1.

The current macOS package doesn't include this update. There will be a new release this week, bringing new features including this one. 

Thank you for your patience, do not hesitate to share any other issue/idea you encounter. :)

**Comment by albemala** [comment]
That's great, thank you! I'll wait for the new release then.
