### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by julianorafael** [eveningkid/reacto#15]
Does it work for React Native too?
I tried to open a current RN project and it didn't go well. What do you it would take to support React Native? I'm seriously interested in this.
Awesome stuff man, keep it up.

**Comment by eveningkid** [comment]
I haven't tried any react native project with reacto. What do you mean "it didn't go well"? Any precise feedback? :)
I remember there is an editor called deco for react native development. 
For now, the project is focused on regular react code but I have no doubts that it could be extended to react native. 

Thanks for the kind words, I really appreciate it! Feel free if you have any other question.
