### ISSUE TITLE
Prettier integration

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#17]
On save or a keyboard shortcut, with ability to customize options.

**Comment by eveningkid** [comment]
Totally agree on this. Something kind of similar to [atom-prettier](https://github.com/prettier/prettier-atom) right?

Regarding the options customization, do you have any precise idea? Should it be directly editable after opening the `.prettierrc`? Or maybe a UI on top of the file (giving suggestions or a list of options)?

So far we agree on these two requirements:
- option: call prettier on "on save" event
- option: call prettier on a given shortcut

Please let me know, I'll be working on this as soon as we have a fixed idea about how it should be!

**Comment by lachlanjc** [comment]
@eveningkid One or the other works for me, I'd prioritize on save, with keyboard shortcut later. I think the MVP for options would be a `.prettierrc` in the user folder, or in some kind of Reacto folder, with a checkbox/select menu UI in Settings later.

**Comment by eveningkid** [comment]
Yes, good idea. I definitely would love having the options inside the "Settings" section and quickly update them + another option to enable/disable prettier.
Alright, I think I have all I need to get started this week. Thanks :)

**Comment by eveningkid** [comment]
Progress for today:
- find Prettier configuration file
- added option "format on save", which works just fine
- now seamless experience when the code is changed (the cursor will remain steady, same for scrollbars)

Todo:
- create configuration file if doesn't exist
- allow to quickly update configuration inside settings (big refactor of `Configurator.jsx` ahead)

![mar-23-2018 00-51-10](https://user-images.githubusercontent.com/7188494/37785142-5c8cd608-2e34-11e8-89c3-bf06cd9ac55a.gif)

**Comment by eveningkid** [comment]
Added with #33
