### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by julianorafael** [eveningkid/reacto#22]
Do you have a roadmap of features and ideas? Where do you think the project will head to?

**Comment by eveningkid** [comment]
I will share a roadmap very soon. I mean to iterate quickly, creating new releases quite often so anyone can quickly give some feedback and suggestions to make it better and right.

I hope this project could be the starting point for anyone looking for a good tool to create react apps. This is the end goal. :)

Stay tuned for the roadmap, I'll soon come up with it. Thanks for asking!

**Comment by julianorafael** [comment]
Awesome. I'll definitely stay tuned and try to contribute to it. :)
