### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by vueu** [eveningkid/reacto#23]
Hey, I'm currently gonna start working on implementing Prettier into this project.

First let's think about the options we'd like to include.

Here's my ideas so far
- Prefer single quotes
- Trailing comma

**Comment by eveningkid** [comment]
Wait, I think I totally misunderstood, I'm so sorry!
I thought you were talking about the prettier integration. I reopen the issue.

**Comment by vueu** [comment]
😂 No worries!

**Comment by eveningkid** [comment]
- tab width: 2
- use tabs: false
- semicolons: true
- use single quotes
- trailing comma if possible (in arrays, objects, ...)
- bracket spacing: true

I guess this would follow the syntax I've tried to respect with this project so far. :)

**Comment by vueu** [comment]
Cool the configuration is good to go. Do you think it would be best to use an approach like [this](https://prettier.io/docs/en/precommit.html)?

**Comment by eveningkid** [comment]
I think the [option 4](https://prettier.io/docs/en/precommit.html#option-4-precise-commits-https-githubcom-jameshenry-precise-commits) is what we need.

**Comment by eveningkid** [comment]
@vueu, are you on it? Let me know, otherwise, I'll close the issue.

**Comment by vueu** [comment]
Yeah I just have an issue at the moment, when you put in a commit, the code gets formatted but it's too late, when you push to GitHub it doesn't contain the formatted code, until you push again.

**Comment by eveningkid** [comment]
Are you still willing to try to debug this? If it doesn't work, don't worry then..

**Comment by vueu** [comment]
Gonna abandon this for now.
