### ISSUE TITLE
Overall Performance

### ISSUE THREAD

**Issue by eveningkid** [eveningkid/reacto#24]
Reacto is slow when dealing with big files. I believe the current pain points lay inside `Editor.jsx`:
- expensive `this.props.updateCode` which slow everything down as it is updating the redux store with a massive new value, many times in a row (despite it is actually `debounce`d right now).
- `this.parseCode` as it generates an ast and pass everything down to the bricks (even it is wrapped inside `perf.debounce` as well).

The problem is that both are necessary. Unless we manage to find another way to call them in a smarter way, or simply rethink about the current workflow.

Has anyone any idea about this? That would be really helpful.

**Comment by eveningkid** [comment]
Little improvement: it used to update twice in a row as `.state.code` and `.state.cursor` would be updated separately (as it was attached to two different listeners). Now do both at once.

**Comment by eveningkid** [comment]
I found the main issue: the editor code zone is controlled for now. I will make changes that will incredibly boost the editor speed performance. Stay tuned, it'll soon be much better. :)

**Comment by eveningkid** [comment]
@lachlanjc, I've just pushed a new build for the project. It is supposed to be way faster than before.
Whenever you have time, could you please download the new release and tell me if the performance has improved? 

[Download new version](https://github.com/eveningkid/reacto/releases/download/v0.1.0/Reacto-0.1.0-updated.dmg)

I remember you mentioned the first release was kind of laggy on your side. 
That would help, thank you. :)

**Comment by lachlanjc** [comment]
@eveningkid Performance is much better in that build! Thank you!
