### ISSUE TITLE
Would it be possible to make this a VSCode plugin?

### ISSUE THREAD

**Issue by hellonearthis** [eveningkid/reacto#25]
This looks cool but would it be possible make this a VSCode plugin?

**Comment by plxel** [comment]
it is IDE, you want IDE as plugin?
if `reacto` will be done well you can use it instead VSCode, Atom etc.

Single features can be implemented as plugins, but I think not in this repo and not by @eveningkid

**Comment by eveningkid** [comment]
Thank you @plxel, you summed it up very well. :)

@hellonearthis, [here was my answer to a similar question](https://medium.com/@eveningkid/i-believe-my-intention-was-different-f004930d0c15) on medium.

I hope that when you'll come back in a few months on this repo, that you'll have a different opinion. Fingers crossed!
