### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by eveningkid** [eveningkid/reacto#26]
Can anyone give it a try and come up with a zip file we can share with the Windows users? That would be sweet.

cc @plxel @gonzalologorg

**Comment by plxel** [comment]
i'll do it

**Comment by plxel** [comment]
@eveningkid where should I send zip?
github allows up to 10 MB

**Comment by eveningkid** [comment]
@plxel maybe post it on google drive and share the link with me! This will be a temporary way for now. :)

**Comment by plxel** [comment]
@eveningkid  [done](https://drive.google.com/file/d/1xnsIXniaMeBAtcBUfpmPPPoTSguV5NmU/view?usp=sharing)

**Comment by eveningkid** [comment]
You're fast, thank you! I'll add it to the readme very soon.

Also, two things:
- did you have anything specific to build it? If so, could you share the steps?
- how is the experience on windows so far? Is it slow? Your feedback is useful.

Thanks again. :)

**Comment by plxel** [comment]
- nothing special, sometime ago (maybe last year) I had problems with node-gyp/node-sass (maybe sometging like @gonzalologorg sees now), but now everything is ok, just `yarn run dist:pack`. 
- app booting time leaves much to be desired, animation between editor and project picker is slow and annoying, font-size or font-family in editor looks strange (or maybe I like font settings in vs code), it can't show me content of node_modules folder, as already said  - scrolls are awful. In one word - there is some work to do :)

**Comment by eveningkid** [comment]
Alright, got it.

- I will sure think of an option to remove the animation, I kind of like it personally. I understand your opinion though.
- font-size and font-family can be changed. Macbook retina screen often makes everything look much better. I guess this must be the reason. If you have any other preference, please share them on an issue and I can manage to set them as defaults for the windows version.
- `node_modules` content is by default hidden as I thought it wasn't necessary. I'll make it as an option as well, to decide whether to ignore it or not.
- scrolls will definitely be improved, no worries.

In one word, I see nothing as impossible! Thanks for your feedback, it will all be better soon.
As soon as the readme will be updated, I'll post here again.

Thank you for your contribution Alexey!

**Comment by plxel** [comment]
@eveningkid I hope I'll have time to help with all this stuff by myself
about `node_modules` - it is visible in leftsidebar, but when I click on it's just change icon. is what you mean by `hidden`?)

**Comment by eveningkid** [comment]
I wish that too, really. You're extremely reactive, it makes me really hopeful for this project. :)

Yes, I mean, empty is more appropriate. I plan to really make it hidden. I personally think that `node_modules` shouldn't be modified as it is supposed to be regenerated after every `yarn install` and kept untracked for git. So seeing it in the file tree is useless in my opinion. For now, the file watcher is simply ignoring the content of `node_modules` this is why it looks "empty".

Now as you mentioned it, I believe it is important to you (and probably not only you) to have it. It'll be in the settings.

**Comment by plxel** [comment]
it is really rare case when i need it
i'm not sure, but this is how it is implemented in vs code (or looks like this) - every folder from .gitignore marked gray in file tree, if i click one - it is loading content of that folder and after that it is in file tree.
