### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by eveningkid** [eveningkid/reacto#27]
Similar to #26, for Linux users. ⚡️

cc @Pegase745 @albemala

**Comment by albemala** [comment]
Here is a build I created for Linux, version 0.1.0 (But from master branch so with all last the last fixes. If you prefer I will build it from tag 0.1.0)

https://drive.google.com/open?id=1VmTgfmg7nWU42lH7fDwK86ogmd6MnOTN

**Comment by eveningkid** [comment]
@albemala how did you actually create a build for Linux? 

I hope we could find a way to automate it with a script, such as calling: `yarn run dist:linux`. 
Anything different inside `package.json`?

That would help, thanks! :)

**Comment by Pegase745** [comment]
@eveningkid I'm on it. I've got a fork ready to build all the things :)

**Comment by albemala** [comment]
The only thing I changed is in the PR I created, linked to this ticket.
Otherwise I just run `yarn dist:pack`
