### ISSUE TITLE
Keyboard shortcuts for switching files

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#29]
Would love to switch between files without my mouse. I suggest Atom/Safari/Chrome's implementation, with <kbd>Cmd-#</kbd> going to tabs 1-8, and <kbd>Cmd-9</kbd> going to the last tab.

**Comment by eveningkid** [comment]
For now, you can switch files using <kbd>Ctrl+Tab</kbd> and <kbd>Ctrl+Tab+Shift</kbd>. You are right about <kbd>Cmd+*</kbd>. I will work on this. Thanks!

**Comment by eveningkid** [comment]
Added with #47 :)

**Comment by lachlanjc** [comment]
Yay!! Thanks @eveningkid :)
