### ISSUE TITLE
Reflect editor status in macOS Close button

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#30]
In fully-native apps (TextEdit, BBEdit, Pages, etc), the red Close stoplight button on macOS gets a black dot inside if the current file has been modified without saving. No idea how/if you can do this in Electron, but it'd be a nice touch. (Certainly not a priority)

**Comment by eveningkid** [comment]
It's actually currently implemented. 

<img width="304" alt="screenshot at mar 25 16-32-58" src="https://user-images.githubusercontent.com/7188494/37873214-371932d2-304a-11e8-9a3f-391f7c179687.png">

I will work on it, I think your impression comes from the fact it is currently not detecting "unsaved changes" until you take your cursor off the editor. This will be fixed, thanks. :)

**Comment by eveningkid** [comment]
Added with #34

**Comment by lachlanjc** [comment]
@eveningkid I discovered this after I submitted this, thanks for updating!
