### ISSUE TITLE
Package Manager: Button to update all dependencies

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#31]
A task I do really often in my terminal is `ncu -a && yarn` (or with `npm i`), which updates all dependencies to their latest versions using [`npm-check-updates`](https://www.npmjs.com/package/npm-check-updates). Would be awesome to have a button for this in the Package Manager!

**Comment by eveningkid** [comment]
**Really nice** suggestion. I didn't know about it. Will definitely add an `update all` button. :)

**Comment by eveningkid** [comment]
By the way, why do we need to call `yarn` after `ncu -a`? It seems that the [`ncu -u` option](https://www.npmjs.com/package/npm-check-updates) does the `package.json` update directly. 

Or was it for a different reason?

**Comment by eveningkid** [comment]
Added with #34.
@lachlanjc waiting for your answer! :)

**Comment by lachlanjc** [comment]
@eveningkid -a updates the dependencies list, but then I need to install the updates + update yarn.lock before I commit.

**Comment by eveningkid** [comment]
Fixed in 594e5e339edad2fcccaebf0a1e0118b753b14596
