### ISSUE TITLE
Fuzzy file search

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#38]
This one will probably be a bunch of work, but it's a real slow-down of using Reacto right now. This is one of the final things before I can switch for my main editor :)

**Comment by eveningkid** [comment]
Please be more precise about what's wrong, what's right, what's missing. Thank you :)
This can definitely be improved, I'm really open to new suggestions!

**Comment by eveningkid** [comment]
@lachlanjc could you please explain more? I'd really want to work on it to make the experience better for you.

**Comment by lachlanjc** [comment]
Hey, sorry I forgot to come back to this. Need Mark as Unread on GitHub.

Basically, a way to open files faster without using the Tree—just start typing (part of) the path to a file, and the editor pulls up a keyboard-navigable list of files that best match that (like `form` finds `src/components/feedback/FeedbackForm.js` or something).

Here's how Atom does it: (<kbd>Cmd-P</kbd>, also used by Xcode, Chrome Dev Tools, etc)
<img width="608" alt="screen shot 2018-03-29 at 9 14 05 pm" src="https://user-images.githubusercontent.com/5074763/38120409-9ea67b36-3396-11e8-8b83-0f96f062e081.png">

And BBEdit's: (<kbd>Cmd-D</kbd>)
<img width="592" alt="screen shot 2018-03-29 at 9 14 56 pm" src="https://user-images.githubusercontent.com/5074763/38120405-98913830-3396-11e8-8ece-5340304a4f88.png">

Sublime Text, Xcode, Safari + Chrome Dev Tools, probably VSCode and the others have this feature and it makes opening/switching files super easy.

**Comment by eveningkid** [comment]
And <kbd>Cmd+F</kbd> on Reacto! 

<img width="604" alt="screenshot at mar 30 11-09-43" src="https://user-images.githubusercontent.com/7188494/38122960-140fc19c-340b-11e8-9468-b5ead71e2a7c.png">

**Comment by eveningkid** [comment]
Is that what you were looking for? :)

**Comment by lachlanjc** [comment]
Is that searching inside files? What I'm talking about just filtering file paths for faster opening/switching.

**Comment by eveningkid** [comment]
It is only checking file paths. It will look up for files inside your file tree...
