### ISSUE TITLE
Add setting to hide .git directory

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#40]

**Comment by eveningkid** [comment]
I believe we should instead add an option to hide any file/directory starting with a dot. 
Otherwise, show it with a higher opacity if the setting is disabled. 
What do you think?

**Comment by Pegase745** [comment]
The idea would be more to hide all files/directories in a .gitignore also

**Comment by eveningkid** [comment]
We'll then have two options: one to hide `.gitignore` files and another for any file starting with a dot. 
I'll keep you updated as soon as it's implemented! :)

**Comment by Dinodanio** [comment]
There are also ci files and environment files with a pre-dot. Files in .gitignore would be great. I think these files are used less then other and cleans the files-structure.

**Comment by eveningkid** [comment]
When I started working on the issue, I realized that this could be part of the git integration inside Reacto. This is the next task I'm working on at the moment. :)

It will soon be added, along with the git integration.

**Comment by eveningkid** [comment]
I integrated details display for a current working project using git. A screenshot can be seen on #73.
For now, files being ignored are still being shown but a little gray left border will be shown.

**Should it be an option to simply not show them inside the file tree?** Thanks for letting me know. :)

**Comment by eveningkid** [comment]
Added with #77!
