### ISSUE TITLE
Error when closing editor

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#43]
I'm getting this error when I close a Reacto project window:
<img width="532" alt="screen shot 2018-03-26 at 1 08 26 am" src="https://user-images.githubusercontent.com/5074763/37887868-41a336ce-3092-11e8-956b-52794cb3bfe5.png">

**Comment by eveningkid** [comment]
Reacto project window = software window? Or did I misunderstand?
If you do try to reproduce the problem, does the alert appear again? I would need more information, please.
It also seems that this occurs in the development version, right?

**Comment by eveningkid** [comment]
As it didn't get more feedback, I guess this wasn't a major issue. 
Please reopen the issue if you have more details about it. Thanks!

**Comment by joshuaquek** [comment]
Latest release working well! Thanks @eveningkid !!
