### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by lachlanjc** [eveningkid/reacto#50]
I know this is significantly Electron's fault, but Reacto uses dramatically more power than other editors. It's likely pretty difficult to optimize and test, but I want to bring it up as a longer-term thing.

I pulled up (production build, not dev) Reacto + BBEdit next to each other, on the same project with the same file, in macOS Split View, running on my 2013 MacBook Pro with Retina Display 13". (Reacto is unusable at smaller window widths due to the sidebar, I know you've added the ability to hide that since this build was released :)
<img width="1280" alt="screen shot 2018-03-29 at 9 23 19 pm" src="https://user-images.githubusercontent.com/5074763/38120542-8aa49b9e-3397-11e8-8553-f1f560e8e97f.png">

Here's Activity Monitor's Energy tab while the two apps are in the foreground. Atom is also Electron-based (same project open there, but in the background), yet uses 1/5 the power.
<img width="815" alt="screen shot 2018-03-29 at 9 21 53 pm" src="https://user-images.githubusercontent.com/5074763/38120564-c36c9670-3397-11e8-8c27-3fa099cf9e95.png">

A moment later, with the apps open but in the background. BBEdit is able to shut down most of what it's running and use almost no power, but Reacto continues using resources.
<img width="815" alt="screen shot 2018-03-29 at 9 22 00 pm" src="https://user-images.githubusercontent.com/5074763/38120588-eb0dc65e-3397-11e8-80f7-b07573f48d26.png">

Finally, here's a moment after both BBEdit and Reacto are minimized in the Dock, doing nothing.
<img width="815" alt="screen shot 2018-03-29 at 9 28 27 pm" src="https://user-images.githubusercontent.com/5074763/38120632-3f40c3d4-3398-11e8-83fd-40a07e3fbdf5.png">

**Comment by eveningkid** [comment]
I will look into it as soon as possible. Totally agree with you. I'm still trying to stay organized and not do anything at the same time.

It should be better anytime soon, thanks for the precise report @lachlanjc! I'll update you as soon as there's progress made. :)

**Comment by lachlanjc** [comment]
@eveningkid Fantastic. Just wanted to bring this to your attention. I think the most important fixes are for when Reacto is in the background/minimized, but there are certainly savings to be made in the active editor as well. Thanks so much for being so responsive and working so hard on this project!

**Comment by eveningkid** [comment]
Alright, sorry it's been a while.

Good news though:
<img width="440" alt="screenshot at apr 19 22-26-49" src="https://user-images.githubusercontent.com/7188494/38997872-03416ca0-4421-11e8-8199-35b2b66ff422.png">

I found what was the major problem causing Reacto to use way too much CPU compared to others! It was simply the file watcher that was using polling although it shouldn't. 

I will soon release a new version that will finally be much better! Right now I am working on a lot of things that will for sure bring a much better experience. :)

I'll close the issue. Please give it a try when the new release is out, but it should be working perfectly after I publish changes. ✨

**Comment by lachlanjc** [comment]
Fabulous! Your sustained work on everything is truly impressive. Thank you 😊
