### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'isInstalled' of null

### ISSUE THREAD

**Issue by plxel** [eveningkid/reacto#65]
Hello! [Here](https://github.com/eveningkid/reacto/blob/449079410c144f032d4b24c3c29c415ef881951f/src/components/_containers/EditorWrapper.js#L36) we have `await yarnPackageManager.isAvailable()` and [here](https://github.com/eveningkid/reacto/blob/master/src/components/RecipesPicker/RecipesPicker.jsx#L24) we call `checkAlreadyInstalledRecipes` after 10 seconds timeout which call another function, which use `project.packageManager.isInstalled`. What if first await is not completed?

We got this:
![image](https://user-images.githubusercontent.com/1496959/38472061-df152f5c-3b82-11e8-8b98-299d8e12f272.png)

I didn't dig deeply into `Environment.hasCommand` and why it is not return any result, but i got this error

I think it's not good idea to use timeout there

**Comment by eveningkid** [comment]
Thanks a lot for the input @plxel! You are right, it was a really bad idea to use `setTimeout` here. 
I suggested a fix with #66, please `git pull` and let me know if you still run into any similar issues. :)
Thank you!

**Comment by eveningkid** [comment]
If you run into the same issue again, please reopen the issue. I consider it as fixed for now.
