### ISSUE TITLE
Changing font ability

### ISSUE THREAD

**Issue by 3dos** [eveningkid/reacto#67]
Is there a way to change the IDE font ? If not, it could be an enhancement to have, let's say, the glorious Operator Mono font!

**Comment by eveningkid** [comment]
There is no way to change the font at the moment. It's sure possible to make this happen though. :)
However, it seems that the Operator Mono font isn't free, isn't it? 
If you have any other font idea, suggestions are very welcome! 
Please let me know so I can add this to the editor, thank you!

**Comment by 3dos** [comment]
Indeed not free but having the ability to use it for users who bought it could be a nice touch.

I found a version of this font on [github](https://github.com/piq9117/operator-mono-nerdfont) but I must admit I don't know if it is legit as it looks pretty much the same as the original Operator Mono.

Thank you for creating this IDE or might I say, idea :D

**Comment by eveningkid** [comment]
> Indeed not free but having the ability to use it for users who bought it could be a nice touch.

Could you share a quick workflow for that? Like you select any local font and apply it to the editor? Or use a URL? 

I like the idea but I hope we could have a more precise user experience here to make this simple for anyone. Something similar to [this Atom package](https://atom.io/packages/fonts) maybe?

As a quick setting inside the preferences menu?

**Comment by 3dos** [comment]
I had in mind a quick setting inside the preferences menu. Since you reference Atom here, I think the support for alternative fonts in Atom is native and works like this :

a text input is there in the settings and you can enter any font name you have installed on your OS. If font cannot be found, simply fallback to the default one.

Does this look viable ?

I would gladly throw myself into resolving this feature but have not much spare time in the upcoming days. I'll check on this as soon as I have time to if no one else did :)

**Comment by eveningkid** [comment]
You're right, let's do this. I'll work on it tonight. Keep you updated. :)

**Comment by eveningkid** [comment]
It should be working now. You simply need to open preferences, type your font name and open another file. The new font should show up.

If you encounter any issue, please let me know. The feature is only available for now if you run the development version and `git pull`.

Otherwise, it'll be available in the next release. :)

**Comment by 3dos** [comment]
Wow, that was fast! I'll try this as soon as I can.

**Comment by 3dos** [comment]
I'm not familiar at all with electron (I never had the chance to try it) but when I hit `yarn start` everything looks to compile just fine (with some warnings) but no window shows up. Am I missing something ?

```
Compiled with warnings.

./src/components/_ui/ToolbarButton/ToolbarButton.jsx
  Line 14:  'onClick' is missing in props validation   react/prop-types
  Line 21:  'active' is missing in props validation    react/prop-types
  Line 22:  'children' is missing in props validation  react/prop-types
  Line 23:  'dropdown' is missing in props validation  react/prop-types
  Line 24:  'loaded' is missing in props validation    react/prop-types
  Line 25:  'loading' is missing in props validation   react/prop-types

./src/components/_containers/EditorWrapper.js
  Line 37:  'updatePackageManager' is missing in props validation  react/prop-types
  Line 44:  'updateTaskRunner' is missing in props validation      react/prop-types
  Line 52:  'taskRunner' is missing in props validation            react/prop-types
  Line 68:  'taskRunner.stop' is missing in props validation       react/prop-types

./src/components/FileTree/FileTree.jsx
  Line 44:  'keepTemporaryFile' is missing in props validation  react/prop-types

./src/tools/task-runners/npm/npm.js
  Line 55:  Unexpected console statement  no-console

./src/components/EditorHeader/EditorHeader.jsx
  Line 57:  'ui' is missing in props validation                           react/prop-types
  Line 57:  'ui.isFileTreeOpened' is missing in props validation          react/prop-types
  Line 58:  'toggleIsFileTreeOpened' is missing in props validation       react/prop-types
  Line 64:  'ui.isBrickSelectorOpened' is missing in props validation     react/prop-types
  Line 65:  'toggleIsBrickSelectorOpened' is missing in props validation  react/prop-types

./node_modules/keyv/src/index.js
18:14-40 Critical dependency: the request of a dependency is an expression

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

**Comment by eveningkid** [comment]
Yes, open a new tab and run: `yarn run electron`, and it should be all fine (keep `yarn start` on the other hand)

**Comment by 3dos** [comment]
It works like a charm (the dev env and the font update)

Now, some italic in the code syntax would be perfect. I'll open a new issue for this though :)

Thanks again for your availability!

**Comment by eveningkid** [comment]
Perfect, you're very welcome. :)
