### ISSUE TITLE
Make task runner menu scrollable

### ISSUE THREAD

**Issue by Wragdan** [eveningkid/reacto#68]
When you have a lot of scripts in package.json, the whole app scrolls.

![image](https://user-images.githubusercontent.com/17775924/38567285-ffcf0ddc-3ca2-11e8-8525-41fc7fff7dc9.png)

**Comment by eveningkid** [comment]
Thank you very much for the input, this should definitely be fixed tomorrow. 
I would have never thought there could be so many scripts inside a package.json! Do you think it would be useful to have a search input for available scripts?

**Comment by eveningkid** [comment]
I fixed it with #72. :)

**Comment by Wragdan** [comment]
More than a search option, a filter, like typing "sta" will show only those scripts that start with "sta" ...

**Comment by eveningkid** [comment]
<img width="297" alt="screenshot at apr 13 21-11-54" src="https://user-images.githubusercontent.com/7188494/38736641-507c689c-3f5f-11e8-985f-f7f8fa78a03f.png">
