### ISSUE TITLE
Window version not working

### ISSUE THREAD

**Issue by indiakamlesh** [eveningkid/reacto#69]
To my delight, today I found that we have now option to install on Windows. Thanks you @eveningkid .

I am facing issue where I am not able to do anything like creating new files. Only black screen coming. I am providing the screenshot how it is looking after installation.

Thanks again for making this and then for window setup. I know it will be resolved soon.
![capture](https://user-images.githubusercontent.com/7062244/38606008-8ec933c4-3d92-11e8-83dd-a0ad133fd4d0.PNG)

**Comment by eveningkid** [comment]
Thank you for your kind words. You should also thank @Pegase745, @plxel, and @albemala who mostly contributed to making Reacto available on all platforms. :)

I sadly have no way to test it on Windows. Two leads to work on this:
- open the development tools console (View, Toggle Developer Tools) and share a screenshot of what you see
- inside the developer tools, open the `Application` tab and let me know if the service worker is listed or not (please find a screenshot below):
<img width="589" alt="screenshot at apr 11 22-15-40" src="https://user-images.githubusercontent.com/7188494/38622493-e30f79f0-3dd5-11e8-8e9c-76228f42c3a0.png">

Hope we can fix this for you!

cc @plxel, have you experienced the same issue? It looks really odd, what do you think? 😕

**Comment by Pegase745** [comment]
@indiakamlesh works for me on Windows 10

**Comment by plxel** [comment]
so..
I got this behavior if I run `yarn start`, and without waiting for dev server start run `yarn run electron`
Reacto is started, but nothing is working

**Comment by eveningkid** [comment]
I'll generate new releases with the updated version. 

@indiakamlesh, please uninstall Reacto and [download the latest release](https://github.com/eveningkid/reacto/releases) (it should be available from one hour after I post this message).

Feel free to reopen the issue if that patch doesn't fix your problem!
