### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node' after installation

### ISSUE THREAD

**Issue by lgarest** [eveningkid/reacto#78]
Hey I was curious about your Reacto project and gave it a try.

I cloned your repo and followed your installation steps, after `yarn install` everything was looking fine but once I run `yarn run electron:dev` I get the `Error: Cannot find module '../build/Debug/nodegit.node'` error. This happens as well for me if I run the project separately as you recommand.

I'm running a macOS High Sierra v10.13.3 and the node version of this error is v8.9.4. Probably is some unhandled dependency but...

Here is the screenshot with the stacktrace:
<img width="809" alt="screen shot 2018-04-26 at 09 47 40" src="https://user-images.githubusercontent.com/1581545/39292587-e8f83cdc-4936-11e8-92a8-d4aea37651cb.png">

**Comment by eveningkid** [comment]
Hi Luis and thanks for sharing!
This issue seems to come from your environment. 

You can try to rebuild the package using the following:
```bash
cd node_modules/nodegit && node-gyp rebuild
```

**Comment by eveningkid** [comment]
@lgarest could you tell me if that worked for you?

**Comment by eveningkid** [comment]
Yes, sure. Could you tell me what worked out for you? :)
I will update the readme file accordingly unless you want to contribute.
Let me know!

**Comment by eveningkid** [comment]
Alright, I referenced this issue in the readme file. Thank you Luis :)
