### ISSUE TITLE
Vibrancy missing on non-macOS devices

### ISSUE THREAD

**Issue by eveningkid** [eveningkid/reacto#8]
I just added a default background that should fix the vibrancy issue on non-macOS devices (c6ba0790aba9923e543eb3feb57fff8063d75bea).

Could anyone try to `git pull`, run the app with `yarn start` and `yarn run electron`, and give me some feedback? That would really help to quickly make the windows/linux versions available.

Thanks!

cc @plxel, @gonzalologorg

**Comment by plxel** [comment]
windows 10
![image](https://user-images.githubusercontent.com/1496959/37650729-cf34aed2-2c46-11e8-9353-90524d5edf7e.png)

**Comment by eveningkid** [comment]
@plxel great, is any other previously blank surface now okay? :)

**Comment by plxel** [comment]
@eveningkid 
i didn't find any other, checked only on windows

**Comment by eveningkid** [comment]
Is the list of bricks more readable now? It used to be all white.

I'm talking about this section:

<img width="408" alt="screenshot at mar 20 19-28-41" src="https://user-images.githubusercontent.com/7188494/37651977-e96b4094-2c74-11e8-9707-69d8162fcfb1.png">

If so, that means it's all good to be packaged for windows. So we could focus on optimisation.

**Comment by plxel** [comment]
![image](https://user-images.githubusercontent.com/1496959/37652120-84e5ec74-2c4b-11e8-9d54-f5049b0540da.png)

items under red arrow - are not clickable using mouse, only using keyboard keys

**Comment by simonhochrein** [comment]
#3

**Comment by plxel** [comment]
@simonhochrein oh, ok
@eveningkid as you can see gray colors are differ from yours

**Comment by eveningkid** [comment]
Great, the background color works well. 

It's kind of dark because the currently opened file isn't a "javascript" file. If you try with a .js, .jsx file, it should look fine. Please let me know so I can close this issue.

The search suggestions elements will soon be clickable with PR #3.

**Comment by plxel** [comment]
@eveningkid right
it's not very good UX) but fine for now i think

**Comment by eveningkid** [comment]
At first, I wanted to hide it when it couldn't be used but I thought changing the opacity was a better idea. 
We'll need to think of a better way indeed, I didn't think this was an issue.

Thanks for the input, this issue is solved then. :)
