### ISSUE TITLE
Can't open or create new file

### ISSUE THREAD

**Issue by safwanolaimat** [eveningkid/reacto#82]
when i call 
reacto in terminal its just opened
can't open or create anything
> you can look here https://ibb.co/bNyQvd

**Comment by eveningkid** [comment]
Hi @husafwan,

Could you give me more information about how to reproduce the issue, please?
I'm from a macOS environment so only a more detailed issue could guide me towards an answer for you.

Let me know. :)

**Comment by husafwan** [comment]
can you give me instruction to install it in right way ?

**Comment by eveningkid** [comment]
Please give me more information about everything: what have you tried so far, what OS are you on...
I can't help you if I don't have any precise explanation.

**Comment by husafwan** [comment]
.AppImage working with me but .deb not working with me
there is no more information tell what you want to know ?

**Comment by eveningkid** [comment]
Could you try to open the developer tools and see if there is any error message? 
It's usually <kbd>Ctrl+Alt+I</kbd>.
