### ISSUE TITLE
Create new one not working on Win7

### ISSUE THREAD

**Issue by Mista-T** [eveningkid/reacto#85]
Hi, thanks for a great tool!

Unfortunately the "Create a new one" option does not seem to do anything on (my) Windows 7 Pro machine. (I haven't tested your app on any other machine yet)
It installed correctly and starts up fine, but then stalls at the "We'll notify you when your new React app is ready" prompt and nothing ever happens...

Thanks for looking into this!

**Comment by eveningkid** [comment]
Hi,

You can try opening the developer tools (just like when using chrome). 
I guess that on Windows it should be <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd>.
Let me know if any error shows up there and then we can keep debugging from that.

Also, thank you for your kind words. Hope we can work that out. :)
