### ISSUE TITLE
Create a way to add a new folder

### ISSUE THREAD

**Issue by jerryturcios08** [eveningkid/reacto#86]
Hello! I have been testing this application with a newly created React project. One thing I've noticed is that one can create a new file by specifying the name of the file along with the absolute path. However, there is no option from what I've seen to create a new folder for a React project. The only way to create a new folder is by doing it through finder (I am using a Mac). It would be useful if this is implemented. Thank you!

**Comment by eveningkid** [comment]
Hi Jerry!
This is a very good suggestion. How come I didn't think of that use case...!
Thank you very much for the input, I'll let you know when it's ready. :)
Have a nice week.

**Comment by eveningkid** [comment]
Now added with #87! Thank you for your help. 
Feel free to share any other idea you have! :)
