### ISSUE TITLE
There's no installer for 32 bits machines, is there?

### ISSUE THREAD

**Issue by manuelcaeiro** [eveningkid/reacto#89]
Reacto seems exactly what I've been looking for (I don't like VS Code and Geany does not seem to have a react plugin) but... I couldn't find an installer for 32 bits machines.
I'm working on old Asus machines, one with Windows 7 and other with Debian 9 - both x86.
:(
Would you consider making a x86 portable for Windows?
Thanks.

**Comment by eveningkid** [comment]
Hi Manuel!

I remember that TravisCI had some trouble generating all the executables (or maybe it wasn't configured well).

What you can do is to `git clone` this repository, then install the project dependencies with `yarn install`.

I believe that if you run `yarn run pack` it should generate an executable for your platform.

Please let me know if that works. :)

**Comment by manuelcaeiro** [comment]
That's a lot of man power :) and a lot of time for someone who has never done that before.
Meanwhile I got Geany to do what I needed. (I don't really use react, it was just an assignment for a course.)
Thanks anyway. Wish you success.

**Comment by eveningkid** [comment]
Perfect, what matters is that you get the right tools to create.

Thank you so much for your kind words!

Have a nice day Manuel :)
