### ISSUE TITLE
BROWSER not recognized as an internal or external command

### ISSUE THREAD

**Issue by plxel** [eveningkid/reacto#9]
Running start script `BROWSER=none yarn start:all` throws error message `BROWSER not recognized as an internal or external command`. 

OS: Windows 10

as i understand BROWSER is env variable, on windows I usually use cross-env package for handling env variables 

relates to https://github.com/eveningkid/reacto/issues/4

**Comment by eveningkid** [comment]
Thanks for letting me know. I will look into it and create a PR. :)
I'll update the issue when it's done.

**Comment by plxel** [comment]
@eveningkid  i think it will be good practice to assign somebody to issue so if anyone see it - will know that this issue in progress and who is working on it

**Comment by eveningkid** [comment]
You're right, I'll keep it in mind from now on. Thank you!
Bug fixed with 9c2a275ec0e1b32f0dc3b6a776802206e8e59e73.

**Comment by dilipkumar0709** [comment]
![WhatsApp Image 2020-07-20 at 12 46 54 AM](https://user-images.githubusercontent.com/54902573/87883096-89ee0e00-ca22-11ea-96f4-7fef6ce5295a.jpeg)
.please help me
