### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [eveningkid/reacto#90]
https://travis-ci.org/eveningkid/reacto/builds/382200247

**Comment by eveningkid** [comment]
Hello,

Sorry for the delay, and thanks a lot for the heads-up Daniel.

However, I should mention somewhere that Reacto is not being maintained. It is a lot of work for one person and this was the reason I could not keep working on it.

I will make this much clearer in the readme. Sorry again for the confusion!

Have a good day :)
